bundle install [--binstubs [= DIRECTORIO]]
                 [--limpiar]
                 [--despliegue]
                 [--fuerza]
                 [--congelado]
                 [--full-index]
                 [--gemfile = GEMFILE]
                 [--jobs = NÚMERO]
                 [--local]
                 [--no-cache]
                 [- no podar]
                 [--path PATH]
                 [--tranquilo]
                 [--retry = NUMBER]
                 [--el asunto]
                 [- independiente [= GRUPO [GRUPO ...]]]
                 [--sistema]
                 [--trust-policy = POLÍTICA]
                 [--with = GROUP [GROUP ...]]
                 [--without = GROUP [GROUP ...]]
